blueprint:
  name: Sync Two Switches Bidirectional (Tuya ↔ Sonoff, anti-loop)
  description: >
    Sincroniza ON/OFF en ambas direcciones entre dos entidades switch (por ejemplo Tuya y Sonoff),
    evitando bucles. Incluye debounce opcional para filtrar rebotes cloud.
  domain: automation
  input:
    tuya_switch:
      name: Switch A (ej. Tuya)
      selector:
        entity:
          domain: switch
    sonoff_switch:
      name: Switch B (ej. Sonoff)
      selector:
        entity:
          domain: switch
    debounce:
      name: Debounce (segundos)
      description: Retraso opcional para filtrar rebotes rápidos. 0–2s recomendado.
      default: 0.2
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: s

mode: queued
max_exceeded: silent

# ──────────────── TRIGGERS con IDs (no templates) ─────────────────
trigger:
  # TUYA
  - platform: state
    id: tuya_on
    entity_id: !input tuya_switch
    to: "on"
    for: { seconds: !input debounce }

  - platform: state
    id: tuya_off
    entity_id: !input tuya_switch
    to: "off"
    for: { seconds: !input debounce }

  # SONOFF
  - platform: state
    id: sonoff_on
    entity_id: !input sonoff_switch
    to: "on"
    for: { seconds: !input debounce }

  - platform: state
    id: sonoff_off
    entity_id: !input sonoff_switch
    to: "off"
    for: { seconds: !input debounce }

condition: []

# ──────────────── ACCIONES (sin templates) ─────────────────
action:
  - choose:

      # ===== A) TUYA → SONOFF =====
      - conditions:
          - condition: trigger
            id: tuya_on
          # Validar que Sonoff está en 'on' o 'off'
          - condition: or
            conditions:
              - condition: state
                entity_id: !input sonoff_switch
                state: "on"
              - condition: state
                entity_id: !input sonoff_switch
                state: "off"
          # Evitar bucle: actuar solo si Sonoff NO está ya 'on'
          - condition: not
            conditions:
              - condition: state
                entity_id: !input sonoff_switch
                state: "on"
        sequence:
          - service: switch.turn_on
            target: { entity_id: !input sonoff_switch }

      - conditions:
          - condition: trigger
            id: tuya_off
          - condition: or
            conditions:
              - condition: state
                entity_id: !input sonoff_switch
                state: "on"
              - condition: state
                entity_id: !input sonoff_switch
                state: "off"
          - condition: not
            conditions:
              - condition: state
                entity_id: !input sonoff_switch
                state: "off"
        sequence:
          - service: switch.turn_off
            target: { entity_id: !input sonoff_switch }

      # ===== B) SONOFF → TUYA =====
      - conditions:
          - condition: trigger
            id: sonoff_on
          - condition: or
            conditions:
              - condition: state
                entity_id: !input tuya_switch
                state: "on"
              - condition: state
                entity_id: !input tuya_switch
                state: "off"
          - condition: not
            conditions:
              - condition: state
                entity_id: !input tuya_switch
                state: "on"
        sequence:
          - service: switch.turn_on
            target: { entity_id: !input tuya_switch }

      - conditions:
          - condition: trigger
            id: sonoff_off
          - condition: or
            conditions:
              - condition: state
                entity_id: !input tuya_switch
                state: "on"
              - condition: state
                entity_id: !input tuya_switch
                state: "off"
          - condition: not
            conditions:
              - condition: state
                entity_id: !input tuya_switch
                state: "off"
        sequence:
          - service: switch.turn_off
            target: { entity_id: !input tuya_switch }
