alias: Atardecer Inteligente
description: >
  Activa escena de anochecer 30 min despu茅s del ocaso.
  Si Nico no est谩 en casa, inicia simulaci贸n de presencia y notifica.
  
trigger:
  - platform: sun
    event: sunset
    offset: "00:30:00"

condition: []

action:
  # 1. Activar escena de anochecer
  - service: scene.turn_on
    target:
      entity_id: scene.anochecer
  
  # 2. Log de inicio
  - service: logbook.log
    data:
      name: "Atardecer Inteligente"
      message: "Escena de anochecer activada - Verificando presencia"
  
  # 3. Verificar si Nico est谩 en casa
  - choose:
      # Si NO est谩 en casa (m谩s de 100m)
      - conditions:
          - condition: template
            value_template: >-
              {{ (distance('device_tracker.blacky', 'zone.home') | float(0)) > 0.1 }}
        sequence:
          # Activar simulaci贸n de presencia
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.presence_simulation
          
          # Log
          - service: logbook.log
            data:
              name: "Atardecer Inteligente"
              message: >-
                Simulaci贸n de presencia iniciada - Nico fuera de casa
                ({{ (distance('device_tracker.blacky', 'zone.home') * 1000) | round(0) }} m)
          
          # Notificar
          - service: notify.mobile_app_blacky
            data:
              title: " Atardecer - Simulaci贸n Activada"
              message: >-
                Se activ贸 la escena de anochecer y la simulaci贸n de presencia
                porque no est谩s en casa. Distancia: {{ (distance('device_tracker.blacky', 'zone.home') * 1000) | round(0) }} m
              data:
                push:
                  interruption-level: time-sensitive
                actions:
                  - action: "STOP_SIMULATION"
                    title: "Detener simulaci贸n"
    
    # Si S est谩 en casa
    default:
      # Log
      - service: logbook.log
        data:
          name: "Atardecer Inteligente"
          message: "Escena activada - Nico en casa, sin simulaci贸n"
      
      # Notificaci贸n opcional (comentada por defecto)
      # - service: notify.mobile_app_blacky
      #   data:
      #     title: " Atardecer"
      #     message: "Escena de anochecer activada. Est谩s en casa."

mode: single

