version: "3.9"

# ════════════════════════════════════════════════════════════════════════════
# FRIGATE - Docker Compose Configuration
# ════════════════════════════════════════════════════════════════════════════
#
# INSTALACIÓN:
# 1. Copiar este archivo a /home/nico/frigate/docker-compose.yml
# 2. Crear config/config.yml con la configuración de cámaras
# 3. docker-compose up -d
#
# ════════════════════════════════════════════════════════════════════════════

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    
    # ──────────────────────────────────────────────────────────────────────
    # PERMISOS
    # ──────────────────────────────────────────────────────────────────────
    privileged: true
    
    # Si tienes Google Coral USB TPU, descomentar:
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb
    #   - /dev/apex_0:/dev/apex_0  # Coral Edge TPU
    
    # ──────────────────────────────────────────────────────────────────────
    # VOLÚMENES
    # ──────────────────────────────────────────────────────────────────────
    volumes:
      # Zona horaria del sistema
      - /etc/localtime:/etc/localtime:ro
      
      # Configuración de Frigate
      - ./config:/config
      
      # Media (grabaciones, snapshots, clips)
      - ./media:/media/frigate
      
      # Cache en tmpfs (RAM) para mejor rendimiento
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000  # 1GB de RAM para cache
    
    # ──────────────────────────────────────────────────────────────────────
    # PUERTOS
    # ──────────────────────────────────────────────────────────────────────
    ports:
      - "5000:5000"        # UI Web de Frigate
      - "8554:8554"        # RTSP feeds (restream)
      - "8555:8555/tcp"    # WebRTC
      - "8555:8555/udp"    # WebRTC
      - "1984:1984"        # GO2RTC API
    
    # ──────────────────────────────────────────────────────────────────────
    # VARIABLES DE ENTORNO
    # ──────────────────────────────────────────────────────────────────────
    environment:
      # Zona horaria
      - TZ=America/Santiago
      
      # Password para streams RTSP de Frigate
      - FRIGATE_RTSP_PASSWORD=mipassword123
      
      # Nivel de logging (debug, info, warning, error)
      - FRIGATE_LOG_LEVEL=info
      
      # Usar hardware acceleration (si está disponible)
      # VAAPI (Intel integrated graphics)
      # - LIBVA_DRIVER_NAME=i965
      
      # NVIDIA GPU (descomentar si tienes GPU NVIDIA)
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    
    # ──────────────────────────────────────────────────────────────────────
    # LÍMITES DE RECURSOS
    # ──────────────────────────────────────────────────────────────────────
    # Opcional: Limitar uso de CPU/RAM para no saturar el servidor
    deploy:
      resources:
        limits:
          cpus: '2.0'      # Máximo 2 cores de CPU
          memory: 2G       # Máximo 2GB de RAM
        reservations:
          cpus: '0.5'      # Reservar mínimo 0.5 cores
          memory: 512M     # Reservar mínimo 512MB
    
    # ──────────────────────────────────────────────────────────────────────
    # HEALTHCHECK
    # ──────────────────────────────────────────────────────────────────────
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # ──────────────────────────────────────────────────────────────────────
    # SHAREDMEMORY (Importante para múltiples cámaras)
    # ──────────────────────────────────────────────────────────────────────
    shm_size: "256mb"     # Shared memory (aumentar si tienes muchas cámaras)
    
    # ──────────────────────────────────────────────────────────────────────
    # LOGGING
    # ──────────────────────────────────────────────────────────────────────
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ════════════════════════════════════════════════════════════════════════════
# NOTAS:
# ════════════════════════════════════════════════════════════════════════════
#
# 1. ACCESO:
#    - UI Web: http://192.168.1.100:5000
#    - RTSP restream: rtsp://192.168.1.100:8554/camera_name
#
# 2. RECURSOS:
#    - Sin Coral: ~50-100% CPU por cámara
#    - Con Coral: ~5-10% CPU total
#    - RAM: ~500MB-1GB base + cache
#
# 3. CORAL TPU:
#    - Descomentar sección "devices" si tienes Coral USB
#    - En config.yml cambiar detector a "edgetpu"
#    - Reiniciar: docker-compose restart
#
# 4. HARDWARE ACCELERATION:
#    - Intel: Descomentar LIBVA_DRIVER_NAME
#    - NVIDIA: Descomentar NVIDIA_* y agregar runtime: nvidia
#    - Reduce CPU para encode/decode de video
#
# 5. TROUBLESHOOTING:
#    - Ver logs: docker logs -f frigate
#    - Reiniciar: docker-compose restart
#    - Detener: docker-compose down
#    - Ver stats: docker stats frigate
#
# 6. ACTUALIZACIONES:
#    - docker-compose pull
#    - docker-compose up -d
#
# ════════════════════════════════════════════════════════════════════════════

