# ════════════════════════════════════════════════════════════════════════════
# AUTOMATIZACIONES DE MONITORING PARA PRESENCE SIMULATION
# ════════════════════════════════════════════════════════════════════════════
#
# Este package contiene automatizaciones auxiliares que monitorean
# el estado de tu simulación y actualizan los helpers para el dashboard
#
# INSTALACIÓN:
# Opción A - Package:
#   1. Guarda como: /config/packages/presence_simulation_monitoring.yaml
#   2. En configuration.yaml agrega: homeassistant: packages: !include_dir_named packages
#   3. Reinicia Home Assistant
#
# Opción B - Automatizaciones individuales:
#   1. Copia cada automatización a través de la UI
#   2. Configuración → Automatizaciones → Crear Automatización → YAML
#
# ════════════════════════════════════════════════════════════════════════════

automation:
  # ──────────────────────────────────────────────────────────────────────────
  # 1. INICIAR MONITORING - Cuando se activa la simulación
  # ──────────────────────────────────────────────────────────────────────────
  - id: presence_simulation_start_monitoring
    alias: "Presence Sim - Iniciar Monitoring"
    description: "Inicializa contadores cuando se activa la simulación"
    
    trigger:
      - platform: state
        entity_id: input_boolean.presence_simulation
        to: "on"
    
    action:
      # Marcar como activa
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.presence_simulation_running
      
      # Registrar hora de inicio
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.presence_simulation_start_time
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      
      # Resetear contadores
      - service: input_number.set_value
        target:
          entity_id: input_number.presence_simulation_loop_counter
        data:
          value: 0
      
      - service: input_number.set_value
        target:
          entity_id: input_number.presence_simulation_lights_on_count
        data:
          value: 0
      
      # Actualizar estado
      - service: input_text.set_value
        target:
          entity_id: input_text.presence_simulation_status
        data:
          value: "Iniciando..."
      
      - service: input_text.set_value
        target:
          entity_id: input_text.presence_simulation_active_lights
        data:
          value: "Ninguna"

  # ──────────────────────────────────────────────────────────────────────────
  # 2. DETENER MONITORING - Cuando se desactiva la simulación
  # ──────────────────────────────────────────────────────────────────────────
  - id: presence_simulation_stop_monitoring
    alias: "Presence Sim - Detener Monitoring"
    description: "Limpia estado cuando se desactiva la simulación"
    
    trigger:
      - platform: state
        entity_id: input_boolean.presence_simulation
        to: "off"
    
    action:
      # Marcar como inactiva
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.presence_simulation_running
      
      # Actualizar estado
      - service: input_text.set_value
        target:
          entity_id: input_text.presence_simulation_status
        data:
          value: "Detenida"
      
      # Limpiar luces activas
      - service: input_text.set_value
        target:
          entity_id: input_text.presence_simulation_active_lights
        data:
          value: "Ninguna"
      
      - service: input_number.set_value
        target:
          entity_id: input_number.presence_simulation_lights_on_count
        data:
          value: 0

  # ──────────────────────────────────────────────────────────────────────────
  # 3. MONITOREAR SWITCHES - Cuando un switch cambia de estado
  # ──────────────────────────────────────────────────────────────────────────
  # NOTA: Cambia estos entity_id por tus 6 switches reales
  - id: presence_simulation_monitor_lights
    alias: "Presence Sim - Monitorear Switches"
    description: "Trackea qué switches están encendidos"
    
    trigger:
      # ⚠️ MODIFICA ESTOS CON TUS SWITCHES REALES
      - platform: state
        entity_id:
          - switch.3gang_switch_switch_1
          - switch.4gang_switch_2_switch_1
          - switch.sonoff_10025ffc47_1
          - switch.4gang_switch_switch_1
          - switch.3gang_switch_switch_2
          - switch.bedroom_3_switch_switch_1
    
    condition:
      - condition: state
        entity_id: input_boolean.presence_simulation_running
        state: "on"
    
    action:
      # Actualizar timestamp
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.presence_simulation_last_update
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      
      # Registrar qué switch cambió
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: input_text.set_value
                target:
                  entity_id: input_text.presence_simulation_last_light_on
                data:
                  value: "{{ state_attr(trigger.entity_id, 'friendly_name') or trigger.entity_id.split('.')[1] }}"
        default:
          - service: input_text.set_value
            target:
              entity_id: input_text.presence_simulation_last_light_off
            data:
              value: "{{ state_attr(trigger.entity_id, 'friendly_name') or trigger.entity_id.split('.')[1] }}"
      
      # Actualizar lista de switches encendidos
      - service: input_text.set_value
        target:
          entity_id: input_text.presence_simulation_active_lights
        data:
          value: >
            {% set switches = [
              'switch.3gang_switch_switch_1',
              'switch.4gang_switch_2_switch_1',
              'switch.sonoff_10025ffc47_1',
              'switch.4gang_switch_switch_1',
              'switch.3gang_switch_switch_2',
              'switch.bedroom_3_switch_switch_1'
            ] %}
            {% set ns = namespace(list=[]) %}
            {% for switch in switches %}
              {% if is_state(switch, 'on') %}
                {% set name = state_attr(switch, 'friendly_name') or switch.split('.')[1] %}
                {% set ns.list = ns.list + [name] %}
              {% endif %}
            {% endfor %}
            {% if ns.list | length > 0 %}
              {{ ns.list | join(', ') }}
            {% else %}
              Ninguna
            {% endif %}
      
      # Contar switches encendidos
      - service: input_number.set_value
        target:
          entity_id: input_number.presence_simulation_lights_on_count
        data:
          value: >
            {% set switches = [
              'switch.3gang_switch_switch_1',
              'switch.4gang_switch_2_switch_1',
              'switch.sonoff_10025ffc47_1',
              'switch.4gang_switch_switch_1',
              'switch.3gang_switch_switch_2',
              'switch.bedroom_3_switch_switch_1'
            ] %}
            {{ switches | select('is_state', 'on') | list | count }}
      
      # Actualizar estado
      - service: input_text.set_value
        target:
          entity_id: input_text.presence_simulation_status
        data:
          value: "En ejecución"

  # ──────────────────────────────────────────────────────────────────────────
  # 4. ACTUALIZAR CADA MINUTO - Para tiempo transcurrido
  # ──────────────────────────────────────────────────────────────────────────
  - id: presence_simulation_update_runtime
    alias: "Presence Sim - Actualizar Runtime"
    description: "Actualiza el tiempo transcurrido cada minuto"
    
    trigger:
      - platform: time_pattern
        minutes: "/1"
    
    condition:
      - condition: state
        entity_id: input_boolean.presence_simulation_running
        state: "on"
    
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.presence_simulation_last_update
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  # ──────────────────────────────────────────────────────────────────────────
  # 5. BOTÓN DE PARADA DE EMERGENCIA
  # ──────────────────────────────────────────────────────────────────────────
  - id: presence_simulation_emergency_stop
    alias: "Presence Sim - Parada de Emergencia"
    description: "Detiene la simulación y apaga todos los switches inmediatamente"
    
    trigger:
      - platform: state
        entity_id: input_boolean.presence_simulation
        to: "off"
    
    condition:
      - condition: state
        entity_id: input_boolean.presence_simulation_running
        state: "on"
    
    action:
      # Apagar todos los switches inmediatamente
      # ⚠️ MODIFICA ESTOS CON TUS SWITCHES REALES
      - service: switch.turn_off
        target:
          entity_id:
            - switch.3gang_switch_switch_1
            - switch.4gang_switch_2_switch_1
            - switch.sonoff_10025ffc47_1
            - switch.4gang_switch_switch_1
            - switch.3gang_switch_switch_2
            - switch.bedroom_3_switch_switch_1
      
      # Actualizar estado
      - service: input_text.set_value
        target:
          entity_id: input_text.presence_simulation_status
        data:
          value: "Detenida manualmente"
      
      # Marcar como inactiva
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.presence_simulation_running

# ════════════════════════════════════════════════════════════════════════════
# NOTAS IMPORTANTES:
# ════════════════════════════════════════════════════════════════════════════
#
# 1. CAMBIAR ENTITY_IDS:
#    Reemplaza todos los switches de ejemplo por tus switches reales:
#    - switch.3gang_switch_switch_1
#    - switch.4gang_switch_2_switch_1
#    - switch.sonoff_10025ffc47_1
#    - switch.4gang_switch_switch_1
#    - switch.3gang_switch_switch_2
#    - switch.bedroom_3_switch_switch_1
#
# 2. CONTADOR DE LOOPS:
#    El contador de loops debe incrementarse manualmente en tu automatización
#    principal. Para hacer esto, agrega al final de cada loop en tu config:
#    
#    - service: input_number.set_value
#      target:
#        entity_id: input_number.presence_simulation_loop_counter
#      data:
#        value: >
#          {{ states('input_number.presence_simulation_loop_counter') | int + 1 }}
#
# 3. TOTAL DE LOOPS:
#    Configura esto manualmente según tu configuración:
#    - Ve a input_number.presence_simulation_loop_total
#    - Establece el valor igual a tu loop_count
#    - O usa 99 para "infinito"
#
# ════════════════════════════════════════════════════════════════════════════

