alias: Regreso a Casa - Desactivar Simulaci贸n
description: >
  Cuando Nico vuelve a casa, si la simulaci贸n de presencia est谩 activa,
  la desactiva, aplica escena de salida y notifica.

trigger:
  - platform: zone
    entity_id: device_tracker.blacky
    zone: zone.home
    event: enter

condition:
  # Solo ejecutar si la simulaci贸n est谩 activa
  - condition: state
    entity_id: input_boolean.presence_simulation
    state: "on"

action:
  # 1. Log de detecci贸n
  - service: logbook.log
    data:
      name: "Regreso a Casa"
      message: "Nico regres贸 a casa - Desactivando simulaci贸n"
  
  # 2. Desactivar simulaci贸n de presencia
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.presence_simulation
  
  # 3. Esperar 2 segundos para que el blueprint termine correctamente
  - delay:
      seconds: 2
  
  # 4. Activar escena de salida
  # Nota: El blueprint tiene configurada scene.bedtime como exit_scene
  # Se activar谩 autom谩ticamente, pero podemos forzarla aqu铆 si queremos
  - service: scene.turn_on
    target:
      entity_id: scene.bedtime
  
  # 5. Log de finalizaci贸n
  - service: logbook.log
    data:
      name: "Regreso a Casa"
      message: "Simulaci贸n desactivada - Escena de salida aplicada"
  
  # 6. Notificar
  - service: notify.mobile_app_blacky
    data:
      title: " Bienvenido a Casa"
      message: >-
        La simulaci贸n de presencia se desactiv贸 autom谩ticamente
        porque regresaste a casa a las {{ now().strftime('%H:%M') }}.
      data:
        push:
          interruption-level: time-sensitive

mode: single

