esphome:
  name: smartnode1
  friendly_name: Smart Node 1

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "uiBug7J/YQ2WEQwAinei45aUGm7L9cf6Sp82nI4GuIU="

ota:
  - platform: esphome
    password: "fc6b855770911eb3179ff203b83f5ec8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test1 Fallback Hotspot"
    password: "EFM0SoydaFKO"

captive_portal:


# I2S Audio para micrófono INMP441
i2s_audio:
  - id: mic_i2s
    i2s_lrclk_pin: GPIO25  # WS (Word Select)
    i2s_bclk_pin: GPIO26   # SCK (Serial Clock)

# Micrófono INMP441
microphone:
  - platform: i2s_audio
    id: smartnode_mic
    adc_type: external
    i2s_din_pin: GPIO33    # SD (Serial Data)
    pdm: false


# UART para LD2410
uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:

# Parámetros avanzados para el LD2410
sensor:
  - platform: adc
    pin: 32
    name: "Room Brightness"
    update_interval: 5s
    accuracy_decimals: 0
    unit_of_measurement: "%"
    raw: true
    samples: 3
    filters:
      - lambda: 'return round(100.0 - (x * 0.024414062));'

  - platform: dht
    pin: 4  # Cambiado de GPIO5 a GPIO4 (más seguro, evita strapping pin)
    temperature:
      name: "Room Temperature"
    humidity:
      name: "Room Humidity"
    update_interval: 60s

  # Nivel de sonido desde micrófono INMP441
  - platform: template
    name: "Sound Level"
    id: sound_level
    unit_of_measurement: "dB"
    accuracy_decimals: 1
    update_interval: 1s
    icon: "mdi:microphone"
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

# Parámetros principales para el LD2410
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

