blueprint:
  name: SmartNode - Iluminaci칩n Autom치tica por Presencia
  description: |
    Enciende y apaga luces autom치ticamente bas치ndose en la presencia detectada
    por un SmartNode (LD2410) y el nivel de luminosidad ambiente.

    Caracter칤sticas:
    - Enciende la luz solo si est치 oscuro
    - Respuesta r치pida al detectar presencia
    - Apagado autom치tico configurable despu칠s de abandonar
    - Soporte para switches simples y dimmers
    - Configuraci칩n de umbrales de luminosidad

  domain: automation

  input:
    # ====================
    # SENSORES SMARTNODE
    # ====================
    presence_sensor:
      name: Sensor de Presencia
      description: Sensor de presencia del SmartNode (binary_sensor)
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: occupancy
          multiple: false

    brightness_sensor:
      name: Sensor de Luminosidad
      description: Sensor de luminosidad del SmartNode (sensor en %)
      selector:
        entity:
          filter:
            - domain: sensor
          multiple: false

    # ====================
    # DISPOSITIVO DE LUZ
    # ====================
    light_entity:
      name: Luz o Switch
      description: Luz o switch a controlar
      selector:
        entity:
          filter:
            - domain:
              - light
              - switch
          multiple: false

    # ====================
    # CONFIGURACI칍N DE LUZ
    # ====================
    brightness_level:
      name: Nivel de Brillo
      description: Porcentaje de brillo al encender (solo para luces con dimmer)
      default: 80
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    transition_time:
      name: Tiempo de Transici칩n
      description: Tiempo de transici칩n al encender/apagar (segundos)
      default: 1
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "s"
          mode: slider

    # ====================
    # UMBRALES Y DELAYS
    # ====================
    brightness_threshold:
      name: Umbral de Oscuridad
      description: Por debajo de este % de luminosidad se considera oscuro
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

    turn_on_delay:
      name: Delay al Encender
      description: Segundos de espera antes de encender (evita falsos positivos)
      default: 0
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: "s"
          mode: slider

    turn_off_delay:
      name: Delay al Apagar
      description: Segundos despu칠s de no detectar presencia para apagar
      default: 5
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: "s"
          mode: slider

    # ====================
    # OPCIONES AVANZADAS
    # ====================
    enable_manual_override:
      name: Permitir Anulaci칩n Manual
      description: Si se enciende/apaga manualmente, respetar ese estado
      default: true
      selector:
        boolean:

    enable_notifications:
      name: Habilitar Notificaciones
      description: Enviar notificaciones al activarse (칰til para debug)
      default: false
      selector:
        boolean:

    notify_device:
      name: Dispositivo de Notificaci칩n
      description: Dispositivo m칩vil para recibir notificaciones
      default: ""
      selector:
        device:
          filter:
            - integration: mobile_app
          multiple: false

# Variables que se pueden usar en toda la automatizaci칩n
variables:
  presence_entity: !input presence_sensor
  brightness_entity: !input brightness_sensor
  light: !input light_entity
  brightness_pct: !input brightness_level
  transition: !input transition_time
  brightness_limit: !input brightness_threshold
  enable_notify: !input enable_notifications
  notify_dev: !input notify_device
  manual_override: !input enable_manual_override

# ====================
# MODO DE EJECUCI칍N
# ====================
mode: restart
max_exceeded: silent

# ====================
# TRIGGERS
# ====================
trigger:
  # TRIGGER 1: Presencia detectada
  - platform: state
    entity_id: !input presence_sensor
    from: "off"
    to: "on"
    for:
      seconds: !input turn_on_delay
    id: presence_on

  # TRIGGER 2: Presencia perdida
  - platform: state
    entity_id: !input presence_sensor
    from: "on"
    to: "off"
    for:
      seconds: !input turn_off_delay
    id: presence_off

# ====================
# ACCIONES
# ====================
action:
  - choose:
      # ==========================================
      # CASO 1: ENCENDER LUZ (PRESENCIA DETECTADA)
      # ==========================================
      - conditions:
          - condition: trigger
            id: presence_on

          # CONDICI칍N: Debe estar oscuro
          - condition: numeric_state
            entity_id: !input brightness_sensor
            below: !input brightness_threshold

          # CONDICI칍N: La luz debe estar apagada
          - condition: state
            entity_id: !input light_entity
            state: "off"

        sequence:
          # Encender la luz
          - choose:
              # Si es una luz con dimmer
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr(light, 'supported_features') is not none and state_attr(light, 'supported_features') | int | bitwise_and(1) == 1 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness_pct: !input brightness_level
                      transition: !input transition_time

            # Si es un switch o luz simple
            default:
              - service: homeassistant.turn_on
                target:
                  entity_id: !input light_entity

          # Log en el sistema
          - service: logbook.log
            data:
              name: "SmartNode - Luz Autom치tica"
              message: >
                Luz encendida por presencia.
                Luminosidad: {{ states(brightness_entity) }}%
                (umbral: {{ brightness_limit }}%)

          # Notificaci칩n opcional
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ enable_notify and notify_dev != '' }}"
                sequence:
                  - device_id: !input notify_device
                    domain: mobile_app
                    type: notify
                    message: >
                      游눠 Luz encendida autom치ticamente
                      Luminosidad: {{ states(brightness_entity) }}%
                    title: "SmartNode Activo"

      # ==========================================
      # CASO 2: APAGAR LUZ (SIN PRESENCIA)
      # ==========================================
      - conditions:
          - condition: trigger
            id: presence_off

          # CONDICI칍N: La luz debe estar encendida
          - condition: state
            entity_id: !input light_entity
            state: "on"

        sequence:
          # Apagar la luz
          - choose:
              # Si es una luz con transici칩n
              - conditions:
                  - condition: template
                    value_template: "{{ light.split('.')[0] == 'light' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input light_entity
                    data:
                      transition: !input transition_time

            # Si es un switch
            default:
              - service: homeassistant.turn_off
                target:
                  entity_id: !input light_entity

          # Log en el sistema
          - service: logbook.log
            data:
              name: "SmartNode - Luz Autom치tica"
              message: >
                Luz apagada autom치ticamente.
                No se detect칩 presencia por {{ turn_off_delay }}s

          # Notificaci칩n opcional
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ enable_notify and notify_dev != '' }}"
                sequence:
                  - device_id: !input notify_device
                    domain: mobile_app
                    type: notify
                    message: >
                      游깿 Luz apagada autom치ticamente
                      Sin presencia detectada
                    title: "SmartNode Inactivo"



